[workspace]
resolver = "2"
members = [
    "nexus-rt",
    "nexus-tools",
    "nexus-riscv"
]
default-members = [
    "nexus-tools"
]

[workspace.package]
edition = "2021"
version = "0.1.0"
publish = false

[workspace.dependencies]
clap = { version = "4.3", features = ["derive"] }
