[workspace]
resolver = "2"
members = [
    "nexus-rt",
    "nexus-tools",
    "nexus-riscv",
    "nexus-riscv-circuit",
    "msnova",
]
default-members = [
    "nexus-tools"
]

[workspace.package]
edition = "2021"
version = "0.1.0"
publish = false

[workspace.dependencies]
clap = { version = "4.3", features = ["derive"] }


# additional settings in .cargo/config
[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[profile.perf]
inherits = "release"
debug = true
strip = false
