[package]
name = "nexus-riscv-circuit"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
clap.workspace = true

ark-ff.workspace = true
ark-std.workspace = true
ark-bn254.workspace = true

nexus-riscv = { path = "../riscv" }
