[package]
name = "nexus-riscv-circuit"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
clap.workspace = true

ark-ff.workspace = true
ark-test-curves.workspace = true

nexus-riscv = { path = "../riscv" }
