[package]
name = "nexus-riscv"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
clap.workspace = true
serde.workspace = true
elf = { version = "0.7", default-features = false, features = ["std"] }

ark-ff.workspace = true
ark-relations.workspace = true
ark-r1cs-std.workspace = true
ark-serialize.workspace = true
ark-bn254.workspace = true
ark-crypto-primitives.workspace = true

[dev-dependencies]
ark-std.workspace = true
